/* Generated by tools/fetch-expedition-photos.mjs — do not edit by hand.
   Empty until the fetch-expedition-photos workflow has run: the game shows
   drawn placeholders for any photo that is not here yet. */
window.PHOTO_MANIFEST = {};
