/* Generated by tools/fetch-expedition-satellite.mjs — do not edit by hand.
   Real satellite views of every expedition from NASA's Blue Marble (public domain,
   via the GIBS service), from a hemisphere down to about 200 km across. */
window.SATELLITE_MANIFEST = {
 "serengeti": [
  {
   "file": "serengeti-0.jpg",
   "deg": 90,
   "km": 9982
  },
  {
   "file": "serengeti-1.jpg",
   "deg": 30,
   "km": 3327
  },
  {
   "file": "serengeti-2.jpg",
   "deg": 10,
   "km": 1109
  },
  {
   "file": "serengeti-3.jpg",
   "deg": 4,
   "km": 444
  },
  {
   "file": "serengeti-4.jpg",
   "deg": 2,
   "km": 222
  }
 ],
 "amazon": [
  {
   "file": "amazon-0.jpg",
   "deg": 90,
   "km": 9972
  },
  {
   "file": "amazon-1.jpg",
   "deg": 30,
   "km": 3324
  },
  {
   "file": "amazon-2.jpg",
   "deg": 10,
   "km": 1108
  },
  {
   "file": "amazon-3.jpg",
   "deg": 4,
   "km": 443
  },
  {
   "file": "amazon-4.jpg",
   "deg": 2,
   "km": 222
  }
 ],
 "reef": [
  {
   "file": "reef-0.jpg",
   "deg": 90,
   "km": 9485
  },
  {
   "file": "reef-1.jpg",
   "deg": 30,
   "km": 3162
  },
  {
   "file": "reef-2.jpg",
   "deg": 10,
   "km": 1054
  },
  {
   "file": "reef-3.jpg",
   "deg": 4,
   "km": 422
  },
  {
   "file": "reef-4.jpg",
   "deg": 2,
   "km": 211
  }
 ],
 "arctic": [
  {
   "file": "arctic-0.jpg",
   "deg": 90,
   "km": 2043
  },
  {
   "file": "arctic-1.jpg",
   "deg": 30,
   "km": 681
  },
  {
   "file": "arctic-2.jpg",
   "deg": 10,
   "km": 227
  },
  {
   "file": "arctic-3.jpg",
   "deg": 4,
   "km": 91
  },
  {
   "file": "arctic-4.jpg",
   "deg": 2,
   "km": 45
  }
 ],
 "galapagos": [
  {
   "file": "galapagos-0.jpg",
   "deg": 90,
   "km": 9989
  },
  {
   "file": "galapagos-1.jpg",
   "deg": 30,
   "km": 3330
  },
  {
   "file": "galapagos-2.jpg",
   "deg": 10,
   "km": 1110
  },
  {
   "file": "galapagos-3.jpg",
   "deg": 4,
   "km": 444
  },
  {
   "file": "galapagos-4.jpg",
   "deg": 2,
   "km": 222
  }
 ],
 "himalaya": [
  {
   "file": "himalaya-0.jpg",
   "deg": 90,
   "km": 8821
  },
  {
   "file": "himalaya-1.jpg",
   "deg": 30,
   "km": 2940
  },
  {
   "file": "himalaya-2.jpg",
   "deg": 10,
   "km": 980
  },
  {
   "file": "himalaya-3.jpg",
   "deg": 4,
   "km": 392
  },
  {
   "file": "himalaya-4.jpg",
   "deg": 2,
   "km": 196
  }
 ],
 "sahara": [
  {
   "file": "sahara-0.jpg",
   "deg": 90,
   "km": 8653
  },
  {
   "file": "sahara-1.jpg",
   "deg": 30,
   "km": 2884
  },
  {
   "file": "sahara-2.jpg",
   "deg": 10,
   "km": 961
  },
  {
   "file": "sahara-3.jpg",
   "deg": 4,
   "km": 385
  },
  {
   "file": "sahara-4.jpg",
   "deg": 2,
   "km": 192
  }
 ],
 "yellowstone": [
  {
   "file": "yellowstone-0.jpg",
   "deg": 90,
   "km": 7113
  },
  {
   "file": "yellowstone-1.jpg",
   "deg": 30,
   "km": 2371
  },
  {
   "file": "yellowstone-2.jpg",
   "deg": 10,
   "km": 790
  },
  {
   "file": "yellowstone-3.jpg",
   "deg": 4,
   "km": 316
  },
  {
   "file": "yellowstone-4.jpg",
   "deg": 2,
   "km": 158
  }
 ],
 "antarctica": [
  {
   "file": "antarctica-0.jpg",
   "deg": 90,
   "km": 2103
  },
  {
   "file": "antarctica-1.jpg",
   "deg": 30,
   "km": 701
  },
  {
   "file": "antarctica-2.jpg",
   "deg": 10,
   "km": 234
  },
  {
   "file": "antarctica-3.jpg",
   "deg": 4,
   "km": 93
  },
  {
   "file": "antarctica-4.jpg",
   "deg": 2,
   "km": 47
  }
 ]
};
