/* Generated by tools/fetch-expedition-satellite.mjs — do not edit by hand.
   Real satellite views of every expedition from NASA's Blue Marble (public domain,
   via the GIBS service), from a hemisphere down to about 200 km across. */
window.SATELLITE_MANIFEST = {
 "serengeti": [
  {
   "file": "serengeti-0.jpg",
   "deg": 90,
   "km": 9982,
   "cx": 0.5,
   "cy": 0.5
  },
  {
   "file": "serengeti-1.jpg",
   "deg": 30,
   "km": 3327,
   "cx": 0.5,
   "cy": 0.5
  },
  {
   "file": "serengeti-2.jpg",
   "deg": 10,
   "km": 1109,
   "cx": 0.5,
   "cy": 0.5
  },
  {
   "file": "serengeti-3.jpg",
   "deg": 4,
   "km": 444,
   "cx": 0.5,
   "cy": 0.5
  },
  {
   "file": "serengeti-4.jpg",
   "deg": 2,
   "km": 222,
   "cx": 0.5,
   "cy": 0.5
  }
 ],
 "amazon": [
  {
   "file": "amazon-0.jpg",
   "deg": 90,
   "km": 9972,
   "cx": 0.5,
   "cy": 0.5
  },
  {
   "file": "amazon-1.jpg",
   "deg": 30,
   "km": 3324,
   "cx": 0.5,
   "cy": 0.5
  },
  {
   "file": "amazon-2.jpg",
   "deg": 10,
   "km": 1108,
   "cx": 0.5,
   "cy": 0.5
  },
  {
   "file": "amazon-3.jpg",
   "deg": 4,
   "km": 443,
   "cx": 0.5,
   "cy": 0.5
  },
  {
   "file": "amazon-4.jpg",
   "deg": 2,
   "km": 222,
   "cx": 0.5,
   "cy": 0.5
  }
 ],
 "reef": [
  {
   "file": "reef-0.jpg",
   "deg": 90,
   "km": 9485,
   "cx": 0.6411,
   "cy": 0.5
  },
  {
   "file": "reef-1.jpg",
   "deg": 30,
   "km": 3162,
   "cx": 0.5,
   "cy": 0.5
  },
  {
   "file": "reef-2.jpg",
   "deg": 10,
   "km": 1054,
   "cx": 0.5,
   "cy": 0.5
  },
  {
   "file": "reef-3.jpg",
   "deg": 4,
   "km": 422,
   "cx": 0.5,
   "cy": 0.5
  },
  {
   "file": "reef-4.jpg",
   "deg": 2,
   "km": 211,
   "cx": 0.5,
   "cy": 0.5
  }
 ],
 "arctic": [
  {
   "file": "arctic-0.jpg",
   "deg": 90,
   "km": 2043,
   "cx": 0.5,
   "cy": 0.1311
  },
  {
   "file": "arctic-1.jpg",
   "deg": 30,
   "km": 681,
   "cx": 0.5,
   "cy": 0.3933
  },
  {
   "file": "arctic-2.jpg",
   "deg": 10,
   "km": 227,
   "cx": 0.5,
   "cy": 0.5
  },
  {
   "file": "arctic-3.jpg",
   "deg": 4,
   "km": 91,
   "cx": 0.5,
   "cy": 0.5
  },
  {
   "file": "arctic-4.jpg",
   "deg": 2,
   "km": 45,
   "cx": 0.5,
   "cy": 0.5
  }
 ],
 "galapagos": [
  {
   "file": "galapagos-0.jpg",
   "deg": 90,
   "km": 9989,
   "cx": 0.5,
   "cy": 0.5
  },
  {
   "file": "galapagos-1.jpg",
   "deg": 30,
   "km": 3330,
   "cx": 0.5,
   "cy": 0.5
  },
  {
   "file": "galapagos-2.jpg",
   "deg": 10,
   "km": 1110,
   "cx": 0.5,
   "cy": 0.5
  },
  {
   "file": "galapagos-3.jpg",
   "deg": 4,
   "km": 444,
   "cx": 0.5,
   "cy": 0.5
  },
  {
   "file": "galapagos-4.jpg",
   "deg": 2,
   "km": 222,
   "cx": 0.5,
   "cy": 0.5
  }
 ],
 "himalaya": [
  {
   "file": "himalaya-0.jpg",
   "deg": 90,
   "km": 8821,
   "cx": 0.5,
   "cy": 0.5
  },
  {
   "file": "himalaya-1.jpg",
   "deg": 30,
   "km": 2940,
   "cx": 0.5,
   "cy": 0.5
  },
  {
   "file": "himalaya-2.jpg",
   "deg": 10,
   "km": 980,
   "cx": 0.5,
   "cy": 0.5
  },
  {
   "file": "himalaya-3.jpg",
   "deg": 4,
   "km": 392,
   "cx": 0.5,
   "cy": 0.5
  },
  {
   "file": "himalaya-4.jpg",
   "deg": 2,
   "km": 196,
   "cx": 0.5,
   "cy": 0.5
  }
 ],
 "sahara": [
  {
   "file": "sahara-0.jpg",
   "deg": 90,
   "km": 8653,
   "cx": 0.5,
   "cy": 0.5
  },
  {
   "file": "sahara-1.jpg",
   "deg": 30,
   "km": 2884,
   "cx": 0.5,
   "cy": 0.5
  },
  {
   "file": "sahara-2.jpg",
   "deg": 10,
   "km": 961,
   "cx": 0.5,
   "cy": 0.5
  },
  {
   "file": "sahara-3.jpg",
   "deg": 4,
   "km": 385,
   "cx": 0.5,
   "cy": 0.5
  },
  {
   "file": "sahara-4.jpg",
   "deg": 2,
   "km": 192,
   "cx": 0.5,
   "cy": 0.5
  }
 ],
 "yellowstone": [
  {
   "file": "yellowstone-0.jpg",
   "deg": 90,
   "km": 7113,
   "cx": 0.5,
   "cy": 0.5
  },
  {
   "file": "yellowstone-1.jpg",
   "deg": 30,
   "km": 2371,
   "cx": 0.5,
   "cy": 0.5
  },
  {
   "file": "yellowstone-2.jpg",
   "deg": 10,
   "km": 790,
   "cx": 0.5,
   "cy": 0.5
  },
  {
   "file": "yellowstone-3.jpg",
   "deg": 4,
   "km": 316,
   "cx": 0.5,
   "cy": 0.5
  },
  {
   "file": "yellowstone-4.jpg",
   "deg": 2,
   "km": 158,
   "cx": 0.5,
   "cy": 0.5
  }
 ],
 "antarctica": [
  {
   "file": "antarctica-0.jpg",
   "deg": 90,
   "km": 2103,
   "cx": 0.8519,
   "cy": 0.865
  },
  {
   "file": "antarctica-1.jpg",
   "deg": 30,
   "km": 701,
   "cx": 0.5557,
   "cy": 0.595
  },
  {
   "file": "antarctica-2.jpg",
   "deg": 10,
   "km": 234,
   "cx": 0.5,
   "cy": 0.5
  },
  {
   "file": "antarctica-3.jpg",
   "deg": 4,
   "km": 93,
   "cx": 0.5,
   "cy": 0.5
  },
  {
   "file": "antarctica-4.jpg",
   "deg": 2,
   "km": 47,
   "cx": 0.5,
   "cy": 0.5
  }
 ]
};
