/* ===========================================================
   Number Grid Builder — word data
   -----------------------------------------------------------
   Same idea as the Color Grid, but the columns are NUMBERS:
   a word belongs in column 5 if it HAS 5 letters.

   Nothing here says how long a word is — the game counts the
   letters itself, so a word can never end up in the wrong
   column. To add more starter words just add lines:

     { w: "Creeper", e: "🟩", t: "mine" }
   w = the word
   e = an emoji (optional — leave it out if there's no good one)
   t = which word pack it belongs to (see THEMES below).
       A word with no `t` still works; it just never shows up
       when a pack is selected.

   Only A–Z letters are counted, so spaces, dashes and
   apostrophes are free: "Spider-Man" counts as 9.
   =========================================================== */

/* The columns of the grid. `n` is the number of letters;
   the last one (10) is really "10 or more".
   The hex colours are all dark enough for white text to clear
   4.5:1 contrast — except #ffd23f, which flips to dark ink. */
const LENGTHS = [
  { n: 2,  label: "2",   hex: "#c62d2d", dark: false },
  { n: 3,  label: "3",   hex: "#b45905", dark: false },
  { n: 4,  label: "4",   hex: "#ffd23f", dark: true  },
  { n: 5,  label: "5",   hex: "#2f8d3e", dark: false },
  { n: 6,  label: "6",   hex: "#1e6fd9", dark: false },
  { n: 7,  label: "7",   hex: "#8331ad", dark: false },
  { n: 8,  label: "8",   hex: "#c22e63", dark: false },
  { n: 9,  label: "9",   hex: "#00807f", dark: false },
  { n: 10, label: "10+", hex: "#7a4e33", dark: false }
];

/* Word packs. `id` matches the `t:` on each entry.
   The game adds an "Everything" option itself. */
const THEMES = [
  { id: "animals", label: "Animals",   emoji: "🦊" },
  { id: "food",    label: "Food",      emoji: "🍕" },
  { id: "mine",    label: "Minecraft", emoji: "⛏️" },
  { id: "space",   label: "Space",     emoji: "🚀" },
  { id: "royal",   label: "Princess",  emoji: "👑" },
  { id: "nature",  label: "Nature",    emoji: "🌳" },
  { id: "things",  label: "Everyday",  emoji: "🧸" },
  { id: "big",     label: "Big words", emoji: "🧠" }
];

const ENTRIES = [
  // --- 2 letters ---
  { w: "Ox", e: "🐂", t: "animals" },
  { w: "Ax", e: "🪓", t: "mine" },
  { w: "Up", e: "⬆️", t: "things" },
  { w: "Pi", e: "🥧", t: "big" },
  { w: "Hi", e: "👋", t: "things" },
  { w: "Me", e: "🙋", t: "things" },
  { w: "Oz", e: "🌈", t: "things" },

  // --- 3 letters ---
  { w: "Cat", e: "🐱", t: "animals" },
  { w: "Dog", e: "🐶", t: "animals" },
  { w: "Sun", e: "☀️", t: "space" },
  { w: "Pig", e: "🐷", t: "animals" },
  { w: "Bee", e: "🐝", t: "animals" },
  { w: "Cow", e: "🐄", t: "animals" },
  { w: "Owl", e: "🦉", t: "animals" },
  { w: "Bat", e: "🦇", t: "animals" },
  { w: "Fox", e: "🦊", t: "animals" },
  { w: "Ant", e: "🐜", t: "animals" },
  { w: "Ram", e: "🐏", t: "animals" },
  { w: "Egg", e: "🥚", t: "food" },
  { w: "Jam", e: "🍯", t: "food" },
  { w: "Pie", e: "🥧", t: "food" },
  { w: "Yam", e: "🍠", t: "food" },
  { w: "Fig", e: "🫒", t: "food" },
  { w: "Ice", e: "🧊", t: "nature" },
  { w: "Web", e: "🕸️", t: "nature" },
  { w: "Sky", e: "🌌", t: "space" },
  { w: "Key", e: "🔑", t: "things" },
  { w: "Map", e: "🗺️", t: "things" },
  { w: "Net", e: "🥅", t: "things" },
  { w: "Van", e: "🚐", t: "things" },
  { w: "Zip", e: "🤐", t: "things" },
  { w: "Bus", e: "🚌", t: "things" },
  { w: "Jet", e: "🛩️", t: "things" },
  { w: "Hoe", e: "🪴", t: "mine" },
  { w: "Bed", e: "🛏️", t: "mine" },
  { w: "Ore", e: "🪨", t: "mine" },
  { w: "Hat", e: "🎩", t: "royal" },
  { w: "Gem", e: "💎", t: "royal" },
  { w: "Elf", e: "🧝", t: "royal" },
  { w: "Bow", e: "🎀", t: "royal" },

  // --- 4 letters ---
  { w: "Bear", e: "🐻", t: "animals" },
  { w: "Frog", e: "🐸", t: "animals" },
  { w: "Lion", e: "🦁", t: "animals" },
  { w: "Fish", e: "🐟", t: "animals" },
  { w: "Duck", e: "🦆", t: "animals" },
  { w: "Wolf", e: "🐺", t: "animals" },
  { w: "Crab", e: "🦀", t: "animals" },
  { w: "Goat", e: "🐐", t: "animals" },
  { w: "Cake", e: "🍰", t: "food" },
  { w: "Corn", e: "🌽", t: "food" },
  { w: "Soup", e: "🍲", t: "food" },
  { w: "Milk", e: "🥛", t: "food" },
  { w: "Taco", e: "🌮", t: "food" },
  { w: "Moon", e: "🌕", t: "space" },
  { w: "Star", e: "⭐", t: "space" },
  { w: "Mars", e: "🔴", t: "space" },
  { w: "Rain", e: "🌧️", t: "nature" },
  { w: "Tree", e: "🌳", t: "nature" },
  { w: "Leaf", e: "🍃", t: "nature" },
  { w: "Wind", e: "💨", t: "nature" },
  { w: "Wave", e: "🌊", t: "nature" },
  { w: "Kite", e: "🪁", t: "things" },
  { w: "Jeep", e: "🚙", t: "things" },
  { w: "Ship", e: "🚢", t: "things" },
  { w: "Book", e: "📚", t: "things" },
  { w: "Drum", e: "🥁", t: "things" },
  { w: "Quiz", e: "❓", t: "things" },
  { w: "X-ray", e: "🩻", t: "things" },
  { w: "Iron", e: "🔩", t: "mine" },
  { w: "Cube", e: "🧊", t: "mine" },
  { w: "Coal", e: "⬛", t: "mine" },
  { w: "Gold", e: "🟨", t: "mine" },
  { w: "Sand", e: "🏖️", t: "mine" },
  { w: "Wool", e: "🧶", t: "mine" },
  { w: "Boat", e: "🛶", t: "mine" },
  { w: "Cave", e: "🕳️", t: "mine" },
  { w: "Ruby", e: "❤️", t: "royal" },
  { w: "Gown", e: "👗", t: "royal" },
  { w: "Ring", e: "💍", t: "royal" },
  { w: "King", e: "🤴", t: "royal" },

  // --- 5 letters ---
  { w: "Tiger", e: "🐯", t: "animals" },
  { w: "Zebra", e: "🦓", t: "animals" },
  { w: "Horse", e: "🐴", t: "animals" },
  { w: "Snake", e: "🐍", t: "animals" },
  { w: "Mouse", e: "🐭", t: "animals" },
  { w: "Whale", e: "🐳", t: "animals" },
  { w: "Sheep", e: "🐑", t: "animals" },
  { w: "Koala", e: "🐨", t: "animals" },
  { w: "Otter", e: "🦦", t: "animals" },
  { w: "Apple", e: "🍎", t: "food" },
  { w: "Pizza", e: "🍕", t: "food" },
  { w: "Candy", e: "🍬", t: "food" },
  { w: "Lemon", e: "🍋", t: "food" },
  { w: "Grape", e: "🍇", t: "food" },
  { w: "Melon", e: "🍈", t: "food" },
  { w: "Bread", e: "🍞", t: "food" },
  { w: "Comet", e: "☄️", t: "space" },
  { w: "Venus", e: "🟠", t: "space" },
  { w: "Earth", e: "🌍", t: "space" },
  { w: "Beach", e: "🏖️", t: "nature" },
  { w: "Ocean", e: "🌊", t: "nature" },
  { w: "River", e: "🏞️", t: "nature" },
  { w: "Storm", e: "⛈️", t: "nature" },
  { w: "Cloud", e: "☁️", t: "nature" },
  { w: "Robot", e: "🤖", t: "things" },
  { w: "Ghost", e: "👻", t: "things" },
  { w: "Igloo", e: "🛖", t: "things" },
  { w: "Piano", e: "🎹", t: "things" },
  { w: "Train", e: "🚂", t: "things" },
  { w: "Watch", e: "⌚", t: "things" },
  { w: "Quilt", e: "🧵", t: "things" },
  { w: "Nurse", e: "👩‍⚕️", t: "things" },
  { w: "Torch", e: "🔥", t: "mine" },
  { w: "Sword", e: "⚔️", t: "mine" },
  { w: "Chest", e: "🧰", t: "mine" },
  { w: "Slime", e: "🟢", t: "mine" },
  { w: "Blaze", e: "🔥", t: "mine" },
  { w: "Stone", e: "🪨", t: "mine" },
  { w: "Anvil", e: "🛠️", t: "mine" },
  { w: "Queen", e: "👑", t: "royal" },
  { w: "Crown", e: "👑", t: "royal" },
  { w: "Tiara", e: "👸", t: "royal" },

  // --- 6 letters ---
  { w: "Donkey", e: "🫏", t: "animals" },
  { w: "Kitten", e: "🐈", t: "animals" },
  { w: "Monkey", e: "🐵", t: "animals" },
  { w: "Parrot", e: "🦜", t: "animals" },
  { w: "Rabbit", e: "🐰", t: "animals" },
  { w: "Spider", e: "🕷️", t: "animals" },
  { w: "Turtle", e: "🐢", t: "animals" },
  { w: "Walrus", e: "🦭", t: "animals" },
  { w: "Banana", e: "🍌", t: "food" },
  { w: "Carrot", e: "🥕", t: "food" },
  { w: "Orange", e: "🍊", t: "food" },
  { w: "Cheese", e: "🧀", t: "food" },
  { w: "Yogurt", e: "🥛", t: "food" },
  { w: "Cookie", e: "🍪", t: "food" },
  { w: "Rocket", e: "🚀", t: "space" },
  { w: "Saturn", e: "🪐", t: "space" },
  { w: "Meteor", e: "☄️", t: "space" },
  { w: "Galaxy", e: "🌌", t: "space" },
  { w: "Flower", e: "🌸", t: "nature" },
  { w: "Jungle", e: "🌴", t: "nature" },
  { w: "Forest", e: "🌲", t: "nature" },
  { w: "Desert", e: "🏜️", t: "nature" },
  { w: "Canyon", e: "🏜️", t: "nature" },
  { w: "Guitar", e: "🎸", t: "things" },
  { w: "Hammer", e: "🔨", t: "things" },
  { w: "Violin", e: "🎻", t: "things" },
  { w: "Pencil", e: "✏️", t: "things" },
  { w: "Zipper", e: "🤐", t: "things" },
  { w: "Shovel", e: "🥄", t: "mine" },
  { w: "Bucket", e: "🪣", t: "mine" },
  { w: "Nether", e: "🔥", t: "mine" },
  { w: "Castle", e: "🏰", t: "royal" },
  { w: "Dragon", e: "🐉", t: "royal" },
  { w: "Prince", e: "🤴", t: "royal" },
  { w: "Palace", e: "🏯", t: "royal" },
  { w: "Ribbon", e: "🎀", t: "royal" },
  { w: "Mirror", e: "🪞", t: "royal" },

  // --- 7 letters ---
  { w: "Dolphin", e: "🐬", t: "animals" },
  { w: "Giraffe", e: "🦒", t: "animals" },
  { w: "Hamster", e: "🐹", t: "animals" },
  { w: "Leopard", e: "🐆", t: "animals" },
  { w: "Octopus", e: "🐙", t: "animals" },
  { w: "Penguin", e: "🐧", t: "animals" },
  { w: "Peacock", e: "🦚", t: "animals" },
  { w: "Vulture", e: "🦅", t: "animals" },
  { w: "Cupcake", e: "🧁", t: "food" },
  { w: "Pumpkin", e: "🎃", t: "food" },
  { w: "Popcorn", e: "🍿", t: "food" },
  { w: "Pancake", e: "🥞", t: "food" },
  { w: "Cabbage", e: "🥬", t: "food" },
  { w: "Mercury", e: "🌑", t: "space" },
  { w: "Neptune", e: "🔵", t: "space" },
  { w: "Iceberg", e: "🧊", t: "nature" },
  { w: "Rainbow", e: "🌈", t: "nature" },
  { w: "Volcano", e: "🌋", t: "nature" },
  { w: "Glacier", e: "🧊", t: "nature" },
  { w: "Blossom", e: "🌸", t: "nature" },
  { w: "Balloon", e: "🎈", t: "things" },
  { w: "Monster", e: "👾", t: "things" },
  { w: "Diamond", e: "💎", t: "mine" },
  { w: "Creeper", e: "🟩", t: "mine" },
  { w: "Bedrock", e: "🧱", t: "mine" },
  { w: "Crafter", e: "🪚", t: "mine" },
  { w: "Village", e: "🏘️", t: "mine" },
  { w: "Emerald", e: "💚", t: "mine" },
  { w: "Sapling", e: "🌱", t: "mine" },
  { w: "Pickaxe", e: "⛏️", t: "mine" },
  { w: "Unicorn", e: "🦄", t: "royal" },
  { w: "Slipper", e: "🥿", t: "royal" },

  // --- 8 letters ---
  { w: "Dinosaur", e: "🦕", t: "animals" },
  { w: "Elephant", e: "🐘", t: "animals" },
  { w: "Kangaroo", e: "🦘", t: "animals" },
  { w: "Squirrel", e: "🐿️", t: "animals" },
  { w: "Tortoise", e: "🐢", t: "animals" },
  { w: "Reindeer", e: "🦌", t: "animals" },
  { w: "Hedgehog", e: "🦔", t: "animals" },
  { w: "Sandwich", e: "🥪", t: "food" },
  { w: "Lollipop", e: "🍭", t: "food" },
  { w: "Zucchini", e: "🥒", t: "food" },
  { w: "Asteroid", e: "🪨", t: "space" },
  { w: "Mushroom", e: "🍄", t: "nature" },
  { w: "Sunshine", e: "🌞", t: "nature" },
  { w: "Sunlight", e: "🌤️", t: "nature" },
  { w: "Mountain", e: "🏔️", t: "nature" },
  { w: "Rainfall", e: "🌧️", t: "nature" },
  { w: "Baseball", e: "⚾", t: "things" },
  { w: "Notebook", e: "📓", t: "things" },
  { w: "Football", e: "🏈", t: "things" },
  { w: "Airplane", e: "✈️", t: "things" },
  { w: "Computer", e: "💻", t: "things" },
  { w: "Umbrella", e: "☂️", t: "things" },
  { w: "Obsidian", e: "🟪", t: "mine" },
  { w: "Skeleton", e: "💀", t: "mine" },
  { w: "Redstone", e: "🔴", t: "mine" },
  { w: "Enderman", e: "🟪", t: "mine" },
  { w: "Princess", e: "👸", t: "royal" },
  { w: "Carriage", e: "🛒", t: "royal" },
  { w: "Necklace", e: "📿", t: "royal" },
  { w: "Sparkles", e: "✨", t: "royal" },
  { w: "Ballgown", e: "👗", t: "royal" },

  // --- 9 letters ---
  { w: "Butterfly", e: "🦋", t: "animals" },
  { w: "Crocodile", e: "🐊", t: "animals" },
  { w: "Jellyfish", e: "🪼", t: "animals" },
  { w: "Alligator", e: "🐊", t: "animals" },
  { w: "Chocolate", e: "🍫", t: "food" },
  { w: "Pineapple", e: "🍍", t: "food" },
  { w: "Blueberry", e: "🫐", t: "food" },
  { w: "Raspberry", e: "🍇", t: "food" },
  { w: "Astronaut", e: "👩‍🚀", t: "space" },
  { w: "Telescope", e: "🔭", t: "space" },
  { w: "Spaceship", e: "🚀", t: "space" },
  { w: "Moonlight", e: "🌙", t: "space" },
  { w: "Waterfall", e: "🏞️", t: "nature" },
  { w: "Dandelion", e: "🌼", t: "nature" },
  { w: "Lightning", e: "⚡", t: "nature" },
  { w: "Xylophone", e: "🎼", t: "things" },
  { w: "Adventure", e: "🗺️", t: "things" },
  { w: "Furniture", e: "🪑", t: "things" },
  { w: "Glowstone", e: "💡", t: "mine" },

  // --- 10 or more letters ---
  { w: "Rhinoceros", e: "🦏", t: "animals" },
  { w: "Caterpillar", e: "🐛", t: "animals" },
  { w: "Grasshopper", e: "🦗", t: "animals" },
  { w: "Hippopotamus", e: "🦛", t: "animals" },
  { w: "Strawberry", e: "🍓", t: "food" },
  { w: "Watermelon", e: "🍉", t: "food" },
  { w: "Marshmallow", e: "🍡", t: "food" },
  { w: "Cheeseburger", e: "🍔", t: "food" },
  { w: "Cauliflower", e: "🥦", t: "food" },
  { w: "Constellation", e: "✨", t: "space" },
  { w: "Thunderstorm", e: "⛈️", t: "nature" },
  { w: "Trampoline", e: "🤸", t: "things" },
  { w: "Helicopter", e: "🚁", t: "things" },
  { w: "Basketball", e: "🏀", t: "things" },
  { w: "Skateboard", e: "🛹", t: "things" },
  { w: "Playground", e: "🛝", t: "things" },
  { w: "Toothbrush", e: "🪥", t: "things" },
  { w: "Firefighter", e: "🧑‍🚒", t: "things" },
  { w: "Enchantment", e: "📜", t: "mine" },
  { w: "Wither Storm", e: "💀", t: "mine" },

  // --- Big-words pack (Shannon's tier) — long, tricky, worth saying out loud ---
  { w: "Gnome", e: "🧙", t: "big" },
  { w: "Yacht", e: "⛵", t: "big" },
  { w: "Queue", e: "🚶", t: "big" },
  { w: "Rhythm", e: "🥁", t: "big" },
  { w: "Sphinx", e: "🐈‍⬛", t: "big" },
  { w: "Quixotic", e: "🗡️", t: "big" },
  { w: "Zeitgeist", e: "🕰️", t: "big" },
  { w: "Juxtapose", e: "🔀", t: "big" },
  { w: "Labyrinth", e: "🌀", t: "big" },
  { w: "Serendipity", e: "🍀", t: "big" },
  { w: "Pterodactyl", e: "🦖", t: "big" },
  { w: "Kaleidoscope", e: "🔮", t: "big" },
  { w: "Encyclopedia", e: "📚", t: "big" },
  { w: "Onomatopoeia", e: "💥", t: "big" },
  { w: "Hydroelectric", e: "⚡", t: "big" },
  { w: "Metamorphosis", e: "🦋", t: "big" },
  { w: "Archaeologist", e: "🏺", t: "big" },
  { w: "Extraordinary", e: "🤩", t: "big" },
  { w: "Palaeontology", e: "🦴", t: "big" },
  { w: "Chrysanthemum", e: "🌼", t: "big" },
  { w: "Photosynthesis", e: "🌿", t: "big" },
  { w: "Bioluminescence", e: "🔦", t: "big" }
];
