/* GENERATED by tools/craepets-art/render.py — do not edit.
   Where every clay sprite lives in the sheets in this folder. */
window.CPArt = {
 "cell": 20,
 "frame": [
  16,
  22
 ],
 "frames": [
  "idle",
  "blink",
  "happy",
  "sleep",
  "walk",
  "happywalk"
 ],
 "petpetFrame": [
  8,
  8
 ],
 "sheets": {
  "blorb": {
   "file": "blorb.png",
   "tile": [
    320,
    440
   ],
   "tiles": {
    "blink": [
     2,
     0
    ],
    "blink-id": [
     3,
     0
    ],
    "happy": [
     4,
     0
    ],
    "happy-id": [
     5,
     0
    ],
    "happywalk": [
     2,
     1
    ],
    "happywalk-id": [
     3,
     1
    ],
    "idle": [
     0,
     0
    ],
    "idle-id": [
     1,
     0
    ],
    "sleep": [
     6,
     0
    ],
    "sleep-id": [
     7,
     0
    ],
    "walk": [
     0,
     1
    ],
    "walk-id": [
     1,
     1
    ],
    "wear-beanie": [
     1,
     2
    ],
    "wear-bluescarf": [
     3,
     4
    ],
    "wear-bow": [
     7,
     1
    ],
    "wear-bowtie": [
     4,
     4
    ],
    "wear-bunnyears": [
     6,
     2
    ],
    "wear-chef": [
     2,
     2
    ],
    "wear-cowboy": [
     4,
     2
    ],
    "wear-crown": [
     5,
     1
    ],
    "wear-flowercrown": [
     0,
     2
    ],
    "wear-glasses": [
     6,
     3
    ],
    "wear-halo": [
     2,
     3
    ],
    "wear-heartglasses": [
     0,
     4
    ],
    "wear-helmet": [
     3,
     2
    ],
    "wear-medal": [
     6,
     4
    ],
    "wear-partyhat": [
     6,
     1
    ],
    "wear-pearls": [
     5,
     4
    ],
    "wear-pirate": [
     7,
     2
    ],
    "wear-princess": [
     1,
     3
    ],
    "wear-pumpkinhat": [
     5,
     3
    ],
    "wear-santahat": [
     4,
     3
    ],
    "wear-scarf": [
     2,
     4
    ],
    "wear-starcrown": [
     3,
     3
    ],
    "wear-starglasses": [
     1,
     4
    ],
    "wear-sunglasses": [
     7,
     3
    ],
    "wear-tiara": [
     4,
     1
    ],
    "wear-tophat": [
     5,
     2
    ],
    "wear-wizard": [
     0,
     3
    ]
   }
  },
  "egg": {
   "file": "egg.png",
   "tile": [
    320,
    440
   ],
   "tiles": {
    "crack0": [
     0,
     0
    ],
    "crack0-id": [
     1,
     0
    ],
    "crack1": [
     2,
     0
    ],
    "crack1-id": [
     3,
     0
    ],
    "crack2": [
     4,
     0
    ],
    "crack2-id": [
     5,
     0
    ]
   }
  },
  "flarn": {
   "file": "flarn.png",
   "tile": [
    320,
    440
   ],
   "tiles": {
    "blink": [
     2,
     0
    ],
    "blink-id": [
     3,
     0
    ],
    "happy": [
     4,
     0
    ],
    "happy-id": [
     5,
     0
    ],
    "happywalk": [
     2,
     1
    ],
    "happywalk-id": [
     3,
     1
    ],
    "idle": [
     0,
     0
    ],
    "idle-id": [
     1,
     0
    ],
    "sleep": [
     6,
     0
    ],
    "sleep-id": [
     7,
     0
    ],
    "walk": [
     0,
     1
    ],
    "walk-id": [
     1,
     1
    ],
    "wear-beanie": [
     1,
     2
    ],
    "wear-bluescarf": [
     3,
     4
    ],
    "wear-bow": [
     7,
     1
    ],
    "wear-bowtie": [
     4,
     4
    ],
    "wear-bunnyears": [
     6,
     2
    ],
    "wear-chef": [
     2,
     2
    ],
    "wear-cowboy": [
     4,
     2
    ],
    "wear-crown": [
     5,
     1
    ],
    "wear-flowercrown": [
     0,
     2
    ],
    "wear-glasses": [
     6,
     3
    ],
    "wear-halo": [
     2,
     3
    ],
    "wear-heartglasses": [
     0,
     4
    ],
    "wear-helmet": [
     3,
     2
    ],
    "wear-medal": [
     6,
     4
    ],
    "wear-partyhat": [
     6,
     1
    ],
    "wear-pearls": [
     5,
     4
    ],
    "wear-pirate": [
     7,
     2
    ],
    "wear-princess": [
     1,
     3
    ],
    "wear-pumpkinhat": [
     5,
     3
    ],
    "wear-santahat": [
     4,
     3
    ],
    "wear-scarf": [
     2,
     4
    ],
    "wear-starcrown": [
     3,
     3
    ],
    "wear-starglasses": [
     1,
     4
    ],
    "wear-sunglasses": [
     7,
     3
    ],
    "wear-tiara": [
     4,
     1
    ],
    "wear-tophat": [
     5,
     2
    ],
    "wear-wizard": [
     0,
     3
    ]
   }
  },
  "glimmr": {
   "file": "glimmr.png",
   "tile": [
    320,
    440
   ],
   "tiles": {
    "blink": [
     2,
     0
    ],
    "blink-id": [
     3,
     0
    ],
    "happy": [
     4,
     0
    ],
    "happy-id": [
     5,
     0
    ],
    "happywalk": [
     2,
     1
    ],
    "happywalk-id": [
     3,
     1
    ],
    "idle": [
     0,
     0
    ],
    "idle-id": [
     1,
     0
    ],
    "sleep": [
     6,
     0
    ],
    "sleep-id": [
     7,
     0
    ],
    "walk": [
     0,
     1
    ],
    "walk-id": [
     1,
     1
    ],
    "wear-beanie": [
     1,
     2
    ],
    "wear-bluescarf": [
     3,
     4
    ],
    "wear-bow": [
     7,
     1
    ],
    "wear-bowtie": [
     4,
     4
    ],
    "wear-bunnyears": [
     6,
     2
    ],
    "wear-chef": [
     2,
     2
    ],
    "wear-cowboy": [
     4,
     2
    ],
    "wear-crown": [
     5,
     1
    ],
    "wear-flowercrown": [
     0,
     2
    ],
    "wear-glasses": [
     6,
     3
    ],
    "wear-halo": [
     2,
     3
    ],
    "wear-heartglasses": [
     0,
     4
    ],
    "wear-helmet": [
     3,
     2
    ],
    "wear-medal": [
     6,
     4
    ],
    "wear-partyhat": [
     6,
     1
    ],
    "wear-pearls": [
     5,
     4
    ],
    "wear-pirate": [
     7,
     2
    ],
    "wear-princess": [
     1,
     3
    ],
    "wear-pumpkinhat": [
     5,
     3
    ],
    "wear-santahat": [
     4,
     3
    ],
    "wear-scarf": [
     2,
     4
    ],
    "wear-starcrown": [
     3,
     3
    ],
    "wear-starglasses": [
     1,
     4
    ],
    "wear-sunglasses": [
     7,
     3
    ],
    "wear-tiara": [
     4,
     1
    ],
    "wear-tophat": [
     5,
     2
    ],
    "wear-wizard": [
     0,
     3
    ]
   }
  },
  "petpets": {
   "file": "petpets.png",
   "tile": [
    160,
    160
   ],
   "tiles": {
    "blobbin": [
     2,
     0
    ],
    "duckling": [
     0,
     0
    ],
    "hedge": [
     5,
     0
    ],
    "kit": [
     4,
     0
    ],
    "moth": [
     3,
     0
    ],
    "snail": [
     1,
     0
    ],
    "starling": [
     7,
     0
    ],
    "wisp": [
     6,
     0
    ]
   }
  },
  "puddlepop": {
   "file": "puddlepop.png",
   "tile": [
    320,
    440
   ],
   "tiles": {
    "blink": [
     2,
     0
    ],
    "blink-id": [
     3,
     0
    ],
    "happy": [
     4,
     0
    ],
    "happy-id": [
     5,
     0
    ],
    "happywalk": [
     2,
     1
    ],
    "happywalk-id": [
     3,
     1
    ],
    "idle": [
     0,
     0
    ],
    "idle-id": [
     1,
     0
    ],
    "sleep": [
     6,
     0
    ],
    "sleep-id": [
     7,
     0
    ],
    "walk": [
     0,
     1
    ],
    "walk-id": [
     1,
     1
    ],
    "wear-beanie": [
     1,
     2
    ],
    "wear-bluescarf": [
     3,
     4
    ],
    "wear-bow": [
     7,
     1
    ],
    "wear-bowtie": [
     4,
     4
    ],
    "wear-bunnyears": [
     6,
     2
    ],
    "wear-chef": [
     2,
     2
    ],
    "wear-cowboy": [
     4,
     2
    ],
    "wear-crown": [
     5,
     1
    ],
    "wear-flowercrown": [
     0,
     2
    ],
    "wear-glasses": [
     6,
     3
    ],
    "wear-halo": [
     2,
     3
    ],
    "wear-heartglasses": [
     0,
     4
    ],
    "wear-helmet": [
     3,
     2
    ],
    "wear-medal": [
     6,
     4
    ],
    "wear-partyhat": [
     6,
     1
    ],
    "wear-pearls": [
     5,
     4
    ],
    "wear-pirate": [
     7,
     2
    ],
    "wear-princess": [
     1,
     3
    ],
    "wear-pumpkinhat": [
     5,
     3
    ],
    "wear-santahat": [
     4,
     3
    ],
    "wear-scarf": [
     2,
     4
    ],
    "wear-starcrown": [
     3,
     3
    ],
    "wear-starglasses": [
     1,
     4
    ],
    "wear-sunglasses": [
     7,
     3
    ],
    "wear-tiara": [
     4,
     1
    ],
    "wear-tophat": [
     5,
     2
    ],
    "wear-wizard": [
     0,
     3
    ]
   }
  },
  "snorbit": {
   "file": "snorbit.png",
   "tile": [
    320,
    440
   ],
   "tiles": {
    "blink": [
     2,
     0
    ],
    "blink-id": [
     3,
     0
    ],
    "happy": [
     4,
     0
    ],
    "happy-id": [
     5,
     0
    ],
    "happywalk": [
     2,
     1
    ],
    "happywalk-id": [
     3,
     1
    ],
    "idle": [
     0,
     0
    ],
    "idle-id": [
     1,
     0
    ],
    "sleep": [
     6,
     0
    ],
    "sleep-id": [
     7,
     0
    ],
    "walk": [
     0,
     1
    ],
    "walk-id": [
     1,
     1
    ],
    "wear-beanie": [
     1,
     2
    ],
    "wear-bluescarf": [
     3,
     4
    ],
    "wear-bow": [
     7,
     1
    ],
    "wear-bowtie": [
     4,
     4
    ],
    "wear-bunnyears": [
     6,
     2
    ],
    "wear-chef": [
     2,
     2
    ],
    "wear-cowboy": [
     4,
     2
    ],
    "wear-crown": [
     5,
     1
    ],
    "wear-flowercrown": [
     0,
     2
    ],
    "wear-glasses": [
     6,
     3
    ],
    "wear-halo": [
     2,
     3
    ],
    "wear-heartglasses": [
     0,
     4
    ],
    "wear-helmet": [
     3,
     2
    ],
    "wear-medal": [
     6,
     4
    ],
    "wear-partyhat": [
     6,
     1
    ],
    "wear-pearls": [
     5,
     4
    ],
    "wear-pirate": [
     7,
     2
    ],
    "wear-princess": [
     1,
     3
    ],
    "wear-pumpkinhat": [
     5,
     3
    ],
    "wear-santahat": [
     4,
     3
    ],
    "wear-scarf": [
     2,
     4
    ],
    "wear-starcrown": [
     3,
     3
    ],
    "wear-starglasses": [
     1,
     4
    ],
    "wear-sunglasses": [
     7,
     3
    ],
    "wear-tiara": [
     4,
     1
    ],
    "wear-tophat": [
     5,
     2
    ],
    "wear-wizard": [
     0,
     3
    ]
   }
  },
  "twiggle": {
   "file": "twiggle.png",
   "tile": [
    320,
    440
   ],
   "tiles": {
    "blink": [
     2,
     0
    ],
    "blink-id": [
     3,
     0
    ],
    "happy": [
     4,
     0
    ],
    "happy-id": [
     5,
     0
    ],
    "happywalk": [
     2,
     1
    ],
    "happywalk-id": [
     3,
     1
    ],
    "idle": [
     0,
     0
    ],
    "idle-id": [
     1,
     0
    ],
    "sleep": [
     6,
     0
    ],
    "sleep-id": [
     7,
     0
    ],
    "walk": [
     0,
     1
    ],
    "walk-id": [
     1,
     1
    ],
    "wear-beanie": [
     1,
     2
    ],
    "wear-bluescarf": [
     3,
     4
    ],
    "wear-bow": [
     7,
     1
    ],
    "wear-bowtie": [
     4,
     4
    ],
    "wear-bunnyears": [
     6,
     2
    ],
    "wear-chef": [
     2,
     2
    ],
    "wear-cowboy": [
     4,
     2
    ],
    "wear-crown": [
     5,
     1
    ],
    "wear-flowercrown": [
     0,
     2
    ],
    "wear-glasses": [
     6,
     3
    ],
    "wear-halo": [
     2,
     3
    ],
    "wear-heartglasses": [
     0,
     4
    ],
    "wear-helmet": [
     3,
     2
    ],
    "wear-medal": [
     6,
     4
    ],
    "wear-partyhat": [
     6,
     1
    ],
    "wear-pearls": [
     5,
     4
    ],
    "wear-pirate": [
     7,
     2
    ],
    "wear-princess": [
     1,
     3
    ],
    "wear-pumpkinhat": [
     5,
     3
    ],
    "wear-santahat": [
     4,
     3
    ],
    "wear-scarf": [
     2,
     4
    ],
    "wear-starcrown": [
     3,
     3
    ],
    "wear-starglasses": [
     1,
     4
    ],
    "wear-sunglasses": [
     7,
     3
    ],
    "wear-tiara": [
     4,
     1
    ],
    "wear-tophat": [
     5,
     2
    ],
    "wear-wizard": [
     0,
     3
    ]
   }
  },
  "zibbit": {
   "file": "zibbit.png",
   "tile": [
    320,
    440
   ],
   "tiles": {
    "blink": [
     2,
     0
    ],
    "blink-id": [
     3,
     0
    ],
    "happy": [
     4,
     0
    ],
    "happy-id": [
     5,
     0
    ],
    "happywalk": [
     2,
     1
    ],
    "happywalk-id": [
     3,
     1
    ],
    "idle": [
     0,
     0
    ],
    "idle-id": [
     1,
     0
    ],
    "sleep": [
     6,
     0
    ],
    "sleep-id": [
     7,
     0
    ],
    "walk": [
     0,
     1
    ],
    "walk-id": [
     1,
     1
    ],
    "wear-beanie": [
     1,
     2
    ],
    "wear-bluescarf": [
     3,
     4
    ],
    "wear-bow": [
     7,
     1
    ],
    "wear-bowtie": [
     4,
     4
    ],
    "wear-bunnyears": [
     6,
     2
    ],
    "wear-chef": [
     2,
     2
    ],
    "wear-cowboy": [
     4,
     2
    ],
    "wear-crown": [
     5,
     1
    ],
    "wear-flowercrown": [
     0,
     2
    ],
    "wear-glasses": [
     6,
     3
    ],
    "wear-halo": [
     2,
     3
    ],
    "wear-heartglasses": [
     0,
     4
    ],
    "wear-helmet": [
     3,
     2
    ],
    "wear-medal": [
     6,
     4
    ],
    "wear-partyhat": [
     6,
     1
    ],
    "wear-pearls": [
     5,
     4
    ],
    "wear-pirate": [
     7,
     2
    ],
    "wear-princess": [
     1,
     3
    ],
    "wear-pumpkinhat": [
     5,
     3
    ],
    "wear-santahat": [
     4,
     3
    ],
    "wear-scarf": [
     2,
     4
    ],
    "wear-starcrown": [
     3,
     3
    ],
    "wear-starglasses": [
     1,
     4
    ],
    "wear-sunglasses": [
     7,
     3
    ],
    "wear-tiara": [
     4,
     1
    ],
    "wear-tophat": [
     5,
     2
    ],
    "wear-wizard": [
     0,
     3
    ]
   }
  }
 }
};
