/* Generated by tools/fetch-expedition-panoramas.mjs — do not edit by hand.
   Real 360° photographs from Wikimedia Commons, one per expedition, with their credits. */
window.PANORAMA_MANIFEST = {
 "reef": {
  "file": "reef.jpg",
  "title": "Heron Bommie SVII.jpg",
  "artist": "© Underwater Earth / XL Catlin Seaview Survey / Christophe Bailhache",
  "license": "CC BY-SA 3.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
  "page": "https://commons.wikimedia.org/wiki/File:Heron_Bommie_SVII.jpg",
  "width": 4096,
  "height": 2048
 }
};
