// Inventory and validate generated adventure art; no network or generation calls.
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const base = path.join(root, 'games/adventure');
const output = path.join(base, 'art/generated');
const context = vm.createContext({ window: {} });
for (const file of ['story-data.js', 'stories-long.js']) {
  vm.runInContext(fs.readFileSync(path.join(base, file), 'utf8'), context);
}
const stories = context.window.STORIES;
const selections = JSON.parse(fs.readFileSync(path.join(base, 'art/direction/selections.json')));
const jobs = stories.flatMap(story => Object.entries(story.nodes).map(([id, node]) => {
  // Illustration descriptions guide generation; they contain no executable art.
  // Retain the hash key "art" so existing data-based receipts stay compatible.
  const source = { text: node.text, art: node.illustration, choices: node.choices, end: node.end };
  return {
    storyId: story.id, title: story.title, nodeId: id,
    style: selections.selections.find(s => s.storyId === story.id).id,
    isStart: id === story.start,
    sourceHash: crypto.createHash('sha256').update(JSON.stringify(source)).digest('hex'),
    ...source,
    incoming: Object.entries(story.nodes).filter(([, n]) => n.choices?.some(c => c.to === id))
      .map(([from, n]) => ({ from, text: n.text })),
    file: `${story.id}-${id}.webp`
  };
}));
fs.mkdirSync(output, { recursive: true });
if (process.argv.includes('--inventory')) {
  fs.writeFileSync(path.join(output, 'inventory.json'), JSON.stringify(jobs, null, 2) + '\n');
}
const pages = {};
let total = 0;
for (const story of stories) {
  const done = [];
  for (const job of jobs.filter(j => j.storyId === story.id)) {
    const receiptPath = path.join(output, 'receipts', job.file.replace('.webp', '.json'));
    if (!fs.existsSync(receiptPath)) continue;
    const receipt = JSON.parse(fs.readFileSync(receiptPath));
    const imagePath = path.join(output, job.file);
    if (receipt.sourceHash !== job.sourceHash) throw Error(`Stale source: ${job.file}`);
    if (receipt.reviewed !== true) continue;
    const bytes = fs.readFileSync(imagePath);
    if (bytes.toString('ascii', 0, 4) !== 'RIFF' || bytes.toString('ascii', 8, 12) !== 'WEBP') throw Error(`Invalid WebP: ${job.file}`);
    if (crypto.createHash('sha256').update(bytes).digest('hex') !== receipt.sha256) throw Error(`Image hash mismatch: ${job.file}`);
    if (receipt.style !== job.style) throw Error(`Wrong style: ${job.file}`);
    (pages[story.id] ||= {})[job.nodeId] = `art/generated/${job.file}`;
    done.push(job.nodeId);
  }
  total += done.length;
  console.log(`${story.id}: ${done.length}/${Object.keys(story.nodes).length}`);
}
if (process.argv.includes('--manifest')) {
  const script = `// Generated by tools/adventure-art.mjs --manifest. Reviewed scenes only.\n(function () {\n  const pages = ${JSON.stringify(pages, null, 2)};\n  for (const story of window.STORIES || []) {\n    for (const [id, src] of Object.entries(pages[story.id] || {})) {\n      if (story.nodes[id]) story.nodes[id].img = src;\n    }\n    if (pages[story.id]?.[story.start]) story.coverImg = pages[story.id][story.start];\n  }\n})();\n`;
  fs.writeFileSync(path.join(output, 'manifest.js'), script);
}
console.log(`TOTAL: ${total}/${jobs.length}`);
if (process.argv.includes('--require-complete') && total !== jobs.length) process.exitCode = 1;
