/* ===========================================================
   Word Guess — the word banks, split out so the game logic in
   word-guess.js stays readable.
   -----------------------------------------------------------
   Four difficulty TIERS, so everyone in the house gets words at
   their own level:

     easy   🐣  4 letters, picture-book words        (Ellie, 3)
     normal 🟩  5 letters, everyday words            (Cory, 6)
     tricky 📚  5 letters, ~4th-grade vocabulary     (Jeannie, 7)
     grown  👑  5 letters, real grown-up words       (Shannon)

   Every answer carries an emoji and a MEANING, which the game
   shows the moment the round ends — that's the vocabulary lesson,
   and it's why every single entry needs a real definition rather
   than a riddle.

   To ADD WORDS: drop an entry in the right list below. Guesses
   are validated against the big DICT4/DICT5 lists in
   dictionary.js, so any real English word is typeable already.
   =========================================================== */

/* ---------- 🐣 easy — 4 letters ---------- */
const WG_EASY = [
  { word: "frog", emoji: "🐸", hint: "A green animal that says 'ribbit'" },
  { word: "fish", emoji: "🐟", hint: "It swims and breathes underwater" },
  { word: "star", emoji: "⭐", hint: "A twinkly light in the night sky" },
  { word: "moon", emoji: "🌙", hint: "It glows in the sky at night" },
  { word: "cake", emoji: "🍰", hint: "A sweet treat with candles on birthdays" },
  { word: "bear", emoji: "🐻", hint: "A big furry animal that loves honey" },
  { word: "duck", emoji: "🦆", hint: "A bird that says 'quack'" },
  { word: "tree", emoji: "🌳", hint: "It has leaves, branches and a trunk" },
  { word: "snow", emoji: "❄️", hint: "Cold white fluff that falls in winter" },
  { word: "ball", emoji: "⚽", hint: "You kick or throw this round toy" },
  { word: "king", emoji: "🤴", hint: "A queen's royal partner" },
  { word: "lion", emoji: "🦁", hint: "The big cat that's king of the jungle" },
  { word: "milk", emoji: "🥛", hint: "A white drink cows give us" },
  { word: "rain", emoji: "🌧️", hint: "Water that falls from clouds" },
  { word: "boat", emoji: "⛵", hint: "It floats and carries you on water" },
  { word: "bird", emoji: "🐦", hint: "An animal with feathers that can fly" },
  { word: "swan", emoji: "🦢", hint: "A graceful white water bird" },
  { word: "kite", emoji: "🪁", hint: "You fly this on a windy day" },
  { word: "drum", emoji: "🥁", hint: "You bang it to make a beat" },
  { word: "gold", emoji: "🪙", hint: "Shiny treasure pirates love" },
  { word: "wolf", emoji: "🐺", hint: "A wild animal like a big grey dog" },
  { word: "ship", emoji: "🚢", hint: "A very big boat" },
  { word: "crab", emoji: "🦀", hint: "A beach animal that walks sideways" },
  { word: "deer", emoji: "🦌", hint: "A gentle forest animal with antlers" },
  { word: "goat", emoji: "🐐", hint: "A farm animal that tries to eat everything" },
  { word: "lamb", emoji: "🐑", hint: "A baby sheep" },
  { word: "pony", emoji: "🐴", hint: "A small horse just the right size for kids" },
  { word: "seal", emoji: "🦭", hint: "A whiskery sea animal that claps" },
  { word: "toad", emoji: "🐸", hint: "A bumpy cousin of the frog" },
  { word: "nest", emoji: "🪺", hint: "The home a bird builds" },
  { word: "leaf", emoji: "🍁", hint: "It grows on a tree and falls in autumn" },
  { word: "rose", emoji: "🌹", hint: "A beautiful flower with thorny stems" },
  { word: "corn", emoji: "🌽", hint: "A yellow veggie that grows on a cob" },
  { word: "pear", emoji: "🍐", hint: "A green fruit shaped like a teardrop" },
  { word: "rice", emoji: "🍚", hint: "Tiny white grains you eat with dinner" },
  { word: "soup", emoji: "🍲", hint: "A hot meal you eat with a spoon" },
  { word: "bell", emoji: "🔔", hint: "It rings ding-dong!" },
  { word: "door", emoji: "🚪", hint: "You knock on it before you come in" },
  { word: "lamp", emoji: "🛋️", hint: "A little light for your bedroom" },
  { word: "sock", emoji: "🧦", hint: "You wear it inside your shoe" },
  { word: "coat", emoji: "🧥", hint: "You put it on when it's cold outside" },
  { word: "ring", emoji: "💍", hint: "Shiny jewellery for your finger" },
  { word: "song", emoji: "🎵", hint: "Music with words you can sing" },
  { word: "park", emoji: "🛝", hint: "A place with swings and slides" },
  { word: "farm", emoji: "🚜", hint: "Where crops grow and animals live" },
  { word: "maze", emoji: "🌀", hint: "A twisty puzzle path you can get lost in" },
  { word: "hero", emoji: "🦸", hint: "Someone brave who saves the day" },
  { word: "swim", emoji: "🏊", hint: "Moving through water with your arms and legs" },
  { word: "sled", emoji: "🛷", hint: "You ride it down a snowy hill" },
  { word: "tent", emoji: "⛺", hint: "A cloth house for camping" },
  { word: "gown", emoji: "👗", hint: "A long fancy dress for a party or a ball" },
  { word: "wand", emoji: "🪄", hint: "A magic stick that casts spells" },
  { word: "cape", emoji: "🦸", hint: "The cloth a superhero wears on their back" },
  { word: "hand", emoji: "✋", hint: "The part of you with five fingers" },
  { word: "nose", emoji: "👃", hint: "The part of your face that smells things" },
  { word: "shoe", emoji: "👟", hint: "You put one on each foot" },
  { word: "flag", emoji: "🚩", hint: "Cloth on a pole that stands for a country" },
  { word: "gift", emoji: "🎁", hint: "A wrapped present you give someone" },
  { word: "worm", emoji: "🪱", hint: "A long wiggly animal that lives in soil" },
  { word: "bath", emoji: "🛁", hint: "A tub of warm water you wash in" },
  { word: "cave", emoji: "🕳️", hint: "A big dark hole in a hill or a rock" },
  { word: "pink", emoji: "💗", hint: "The colour of bubblegum and rosy cheeks" },
  { word: "blue", emoji: "💙", hint: "The colour of the sky on a clear day" },
  { word: "bone", emoji: "🦴", hint: "The hard part inside you that holds you up" },
  { word: "wave", emoji: "🌊", hint: "Water rolling up the beach" },
  { word: "kiwi", emoji: "🥝", hint: "A fuzzy brown fruit that's green inside" },
];

/* ---------- 🟩 normal — 5 letters, everyday words ---------- */
const WG_NORMAL = [
  { word: "apple", emoji: "🍎", hint: "A crunchy red or green fruit" },
  { word: "happy", emoji: "😊", hint: "How you feel on your birthday" },
  { word: "water", emoji: "💧", hint: "You drink it when you're thirsty" },
  { word: "candy", emoji: "🍬", hint: "A sweet treat on Halloween" },
  { word: "cloud", emoji: "☁️", hint: "A fluffy white thing in the sky" },
  { word: "dance", emoji: "💃", hint: "Moving your body to music" },
  { word: "dream", emoji: "💤", hint: "A story in your head while you sleep" },
  { word: "eagle", emoji: "🦅", hint: "A huge bird with sharp eyes" },
  { word: "fairy", emoji: "🧚", hint: "A tiny magical creature with wings" },
  { word: "grape", emoji: "🍇", hint: "A small round purple fruit" },
  { word: "heart", emoji: "❤️", hint: "The shape that means love" },
  { word: "juice", emoji: "🧃", hint: "A fruity drink in a box" },
  { word: "lemon", emoji: "🍋", hint: "A sour yellow fruit" },
  { word: "magic", emoji: "✨", hint: "Wizards and fairies use it" },
  { word: "mouse", emoji: "🐭", hint: "A tiny animal that likes cheese" },
  { word: "ocean", emoji: "🌊", hint: "The huge salty water with whales" },
  { word: "panda", emoji: "🐼", hint: "A black-and-white bear that loves bamboo" },
  { word: "queen", emoji: "👑", hint: "A king's royal partner" },
  { word: "robot", emoji: "🤖", hint: "A machine that can move and beep" },
  { word: "snake", emoji: "🐍", hint: "A long animal with no legs" },
  { word: "train", emoji: "🚂", hint: "It runs on tracks: choo-choo!" },
  { word: "zebra", emoji: "🦓", hint: "A striped animal like a horse" },
  { word: "sword", emoji: "⚔️", hint: "A blade knights and Minecraft heroes use" },
  { word: "crown", emoji: "👑", hint: "A queen wears it on her head" },
  { word: "ghost", emoji: "👻", hint: "A friendly-spooky 'boo!' creature" },
  { word: "pizza", emoji: "🍕", hint: "Cheesy round food with slices" },
  { word: "puppy", emoji: "🐶", hint: "A baby dog" },
  { word: "bunny", emoji: "🐰", hint: "A hoppy animal with long ears" },
  { word: "sheep", emoji: "🐑", hint: "A farm animal that says 'baa'" },
  { word: "koala", emoji: "🐨", hint: "A sleepy animal that hugs trees" },
  { word: "plant", emoji: "🪴", hint: "It grows in soil and needs sun" },
  { word: "music", emoji: "🎵", hint: "Songs you listen and dance to" },
  { word: "smile", emoji: "🙂", hint: "What your mouth does when happy" },
  { word: "story", emoji: "📖", hint: "A tale in a book" },
  { word: "beach", emoji: "🏖️", hint: "Sandy place by the sea" },
  { word: "horse", emoji: "🐴", hint: "An animal you can ride that neighs" },
  { word: "house", emoji: "🏠", hint: "The building a family lives in" },
  { word: "light", emoji: "💡", hint: "It helps you see in the dark" },
  { word: "night", emoji: "🌃", hint: "When the sky is dark and stars come out" },
  { word: "party", emoji: "🥳", hint: "A fun celebration with friends" },
  { word: "piano", emoji: "🎹", hint: "A big instrument with black and white keys" },
  { word: "whale", emoji: "🐋", hint: "The biggest animal in the whole ocean" },
  { word: "shark", emoji: "🦈", hint: "A big fish with lots and lots of teeth" },
  { word: "snail", emoji: "🐌", hint: "A slow animal that carries its own house" },
  { word: "spoon", emoji: "🥄", hint: "You eat soup and cereal with it" },
  { word: "sugar", emoji: "🍭", hint: "It makes treats taste sweet" },
  { word: "seven", emoji: "7️⃣", hint: "The number that comes after six" },
  { word: "eight", emoji: "8️⃣", hint: "The number that comes after seven" },
  { word: "green", emoji: "💚", hint: "The colour of grass" },
  { word: "white", emoji: "🤍", hint: "The colour of snow" },
  { word: "brown", emoji: "🤎", hint: "The colour of chocolate" },
  { word: "flute", emoji: "🎶", hint: "A skinny instrument you blow into" },
  { word: "tulip", emoji: "🌷", hint: "A cup-shaped spring flower" },
  { word: "daisy", emoji: "🌼", hint: "A white flower with a yellow middle" },
  { word: "peach", emoji: "🍑", hint: "A fuzzy sweet fruit" },
  { word: "berry", emoji: "🫐", hint: "A tiny sweet fruit" },
  { word: "melon", emoji: "🍈", hint: "A big round juicy fruit" },
  { word: "salad", emoji: "🥗", hint: "A bowl of crunchy healthy veggies" },
  { word: "toast", emoji: "🍞", hint: "Warm crunchy bread for breakfast" },
  { word: "honey", emoji: "🍯", hint: "The sweet sticky food bees make" },
  { word: "lunch", emoji: "🥪", hint: "The meal you eat in the middle of the day" },
  { word: "tooth", emoji: "🦷", hint: "You brush it every morning and night" },
  { word: "smart", emoji: "🧠", hint: "Really good at figuring things out" },
  { word: "quiet", emoji: "🤫", hint: "Making no noise at all — shhh!" },
  { word: "storm", emoji: "⛈️", hint: "Rain, wind and thunder all together" },
  { word: "sunny", emoji: "☀️", hint: "When the sky is full of sunshine" },
  { word: "windy", emoji: "🍃", hint: "Weather that blows your hat off" },
  { word: "earth", emoji: "🌍", hint: "The planet we all live on" },
  { word: "field", emoji: "🌾", hint: "A big open grassy space" },
  { word: "river", emoji: "🏞️", hint: "Water that flows all the way to the sea" },
  { word: "stone", emoji: "🪨", hint: "A small hard rock" },
  { word: "torch", emoji: "🔦", hint: "A light you carry — Minecraft has them!" },
  { word: "wheel", emoji: "🛞", hint: "A round thing that helps cars roll" },
  { word: "clock", emoji: "🕐", hint: "It tells you what time it is" },
  { word: "scarf", emoji: "🧣", hint: "You wrap it round your neck when it's cold" },
  { word: "glove", emoji: "🧤", hint: "It keeps one hand warm" },
  { word: "shoes", emoji: "👟", hint: "You wear them on your feet" },
  { word: "skate", emoji: "⛸️", hint: "Gliding along on ice or wheels" },
  { word: "climb", emoji: "🧗", hint: "Going up a tree or a wall" },
  { word: "paint", emoji: "🎨", hint: "You brush colours onto paper with it" },
  { word: "camel", emoji: "🐫", hint: "A desert animal with humps" },
  { word: "hippo", emoji: "🦛", hint: "A big river animal with a huge mouth" },
  { word: "llama", emoji: "🦙", hint: "A fluffy animal that might spit at you" },
  { word: "otter", emoji: "🦦", hint: "A playful swimmer that floats on its back" },
  { word: "moose", emoji: "🫎", hint: "A huge deer with big flat antlers" },
  { word: "goose", emoji: "🪿", hint: "A big bird that honks" },
  { word: "chick", emoji: "🐤", hint: "A fluffy baby chicken" },
  { word: "witch", emoji: "🧙", hint: "She rides a broom and casts spells" },
  { word: "giant", emoji: "🏔️", hint: "A huge, huge person from fairy tales" },
  { word: "brick", emoji: "🧱", hint: "Builders stack these to make walls" },
  { word: "truck", emoji: "🚚", hint: "A big vehicle that carries heavy things" },
  { word: "plane", emoji: "✈️", hint: "It flies people through the sky" },
  { word: "money", emoji: "💰", hint: "You use it to buy things" },
  { word: "penny", emoji: "🪙", hint: "A tiny coin" },
  { word: "spell", emoji: "🪄", hint: "The magic words a wizard says" },
  { word: "bread", emoji: "🍞", hint: "The baked loaf you make sandwiches from" },
  { word: "chair", emoji: "🪑", hint: "The thing you sit on at the table" },
  { word: "clown", emoji: "🤡", hint: "A funny circus person with a red nose" },
  { word: "dress", emoji: "👗", hint: "Clothing that is a top and skirt in one" },
  { word: "flame", emoji: "🔥", hint: "The bright hot tip of a fire" },
  { word: "jelly", emoji: "🍮", hint: "A sweet wobbly pudding" },
  { word: "kitty", emoji: "🐱", hint: "A cuddly name for a cat" },
  { word: "mango", emoji: "🥭", hint: "A sweet orange fruit from hot countries" },
  { word: "movie", emoji: "🎬", hint: "A story you watch on a screen" },
  { word: "pearl", emoji: "🦪", hint: "A shiny white ball that grows in an oyster" },
  { word: "pilot", emoji: "🧑‍✈️", hint: "The person who flies the plane" },
  { word: "sleep", emoji: "😴", hint: "What you do all night with your eyes shut" },
  { word: "cream", emoji: "🍦", hint: "The thick rich top of the milk" },
  { word: "robin", emoji: "🐦", hint: "A little bird with a red chest" },
  { word: "swing", emoji: "🎠", hint: "A seat on ropes you push back and forth" },
  { word: "tower", emoji: "🗼", hint: "A very tall narrow building" },
  { word: "world", emoji: "🌍", hint: "Everything and everywhere, all together" },
];

/* ---------- 📚 tricky — 5 letters, ~4th-grade vocabulary ---------- */
const WG_TRICKY = [
  { word: "amble", emoji: "🚶", hint: "To walk along in a slow, relaxed way" },
  { word: "blunt", emoji: "🔪", hint: "Not sharp — or saying something very plainly" },
  { word: "brisk", emoji: "🌬️", hint: "Quick and lively, like a fast walk in cold air" },
  { word: "chasm", emoji: "🏞️", hint: "A deep, deep crack in the earth" },
  { word: "clasp", emoji: "🤝", hint: "To hold something tightly, or a clip that fastens" },
  { word: "crave", emoji: "🍪", hint: "To want something very, very badly" },
  { word: "crest", emoji: "🌊", hint: "The very top of a wave, a hill or a helmet" },
  { word: "dwell", emoji: "🏡", hint: "To live somewhere" },
  { word: "elude", emoji: "🫥", hint: "To slip away and not get caught" },
  { word: "ember", emoji: "🔥", hint: "A glowing piece of a fire that is nearly out" },
  { word: "exert", emoji: "💪", hint: "To put in effort or push with force" },
  { word: "flair", emoji: "✨", hint: "A natural talent for doing something well" },
  { word: "fleet", emoji: "⛵", hint: "A group of ships — or moving very fast" },
  { word: "forge", emoji: "⚒️", hint: "To shape hot metal by hammering it" },
  { word: "frail", emoji: "🍂", hint: "Weak and easy to break" },
  { word: "gauge", emoji: "🌡️", hint: "A tool that measures how much of something there is" },
  { word: "glean", emoji: "🌾", hint: "To gather bits of grain or facts, little by little" },
  { word: "grasp", emoji: "✊", hint: "To grab hold of — or to understand something" },
  { word: "gruff", emoji: "🐻", hint: "Rough and grumpy sounding" },
  { word: "hasty", emoji: "🏃", hint: "Done in too much of a hurry" },
  { word: "hoard", emoji: "💎", hint: "A hidden pile of treasure, or to pile things up" },
  { word: "hover", emoji: "🚁", hint: "To stay floating in one spot in the air" },
  { word: "humid", emoji: "💦", hint: "Air that feels sticky and full of water" },
  { word: "ideal", emoji: "🌟", hint: "Exactly as good as something could possibly be" },
  { word: "inept", emoji: "🤷", hint: "Really not good at doing something" },
  { word: "knack", emoji: "🎯", hint: "A clever skill you pick up easily" },
  { word: "latch", emoji: "🚪", hint: "The little catch that holds a gate shut" },
  { word: "lithe", emoji: "🤸", hint: "Bending and moving easily, like a gymnast" },
  { word: "lunar", emoji: "🌕", hint: "To do with the Moon" },
  { word: "mirth", emoji: "😂", hint: "Happy laughing and good cheer" },
  { word: "moist", emoji: "🧁", hint: "A little bit wet, like a good slice of cake" },
  { word: "motif", emoji: "🎨", hint: "A pattern or idea that repeats in art or music" },
  { word: "mural", emoji: "🖼️", hint: "A giant painting made right on a wall" },
  { word: "noble", emoji: "🤴", hint: "Kind and honourable — or a lord or lady" },
  { word: "nudge", emoji: "👉", hint: "A gentle little push" },
  { word: "oasis", emoji: "🌴", hint: "A green watery spot in the middle of a desert" },
  { word: "orbit", emoji: "🪐", hint: "The path something takes around a planet or star" },
  { word: "ounce", emoji: "⚖️", hint: "A small unit of weight" },
  { word: "pluck", emoji: "🪶", hint: "To pull something out quickly — or being brave" },
  { word: "poise", emoji: "🩰", hint: "Standing calm, balanced and steady" },
  { word: "prowl", emoji: "🐈", hint: "To creep around quietly, hunting" },
  { word: "quest", emoji: "🗺️", hint: "A long adventure to find something" },
  { word: "quirk", emoji: "🤪", hint: "A funny little habit that makes someone unique" },
  { word: "realm", emoji: "🏰", hint: "A kingdom, or a whole world of its own" },
  { word: "relic", emoji: "🏺", hint: "Something very old left over from long ago" },
  { word: "rigid", emoji: "🧱", hint: "Stiff and impossible to bend" },
  { word: "roost", emoji: "🐔", hint: "The perch where birds settle down to sleep" },
  { word: "rouse", emoji: "🛌", hint: "To wake someone up or stir them into action" },
  { word: "rural", emoji: "🚜", hint: "To do with the countryside and farms" },
  { word: "scowl", emoji: "😠", hint: "An angry frown" },
  { word: "shrug", emoji: "🤷", hint: "Lifting your shoulders to say 'I don't know'" },
  { word: "siege", emoji: "🏯", hint: "When an army surrounds a castle and waits" },
  { word: "sleek", emoji: "🐬", hint: "Smooth, shiny and built to slip through the air" },
  { word: "smirk", emoji: "😏", hint: "A small, slightly cheeky smile" },
  { word: "spurt", emoji: "⛲", hint: "A sudden burst of liquid or speed" },
  { word: "stale", emoji: "🍞", hint: "Old and dry — not fresh any more" },
  { word: "stern", emoji: "👮", hint: "Serious and strict" },
  { word: "swift", emoji: "🏇", hint: "Very, very fast" },
  { word: "tempo", emoji: "🥁", hint: "How fast or slow a piece of music goes" },
  { word: "thorn", emoji: "🌹", hint: "The sharp prickle on a rose stem" },
  { word: "tidal", emoji: "🌊", hint: "To do with the tide rising and falling" },
  { word: "timid", emoji: "🐭", hint: "Shy and easily frightened" },
  { word: "trait", emoji: "🧬", hint: "A feature that is part of who you are" },
  { word: "trove", emoji: "🪙", hint: "A valuable collection that someone has found" },
  { word: "vapor", emoji: "☁️", hint: "Water that has turned into a gas" },
  { word: "vivid", emoji: "🌈", hint: "Bright, strong and easy to picture" },
  { word: "vocal", emoji: "🎤", hint: "To do with the voice — or speaking up loudly" },
  { word: "wager", emoji: "🎲", hint: "A bet on what is going to happen" },
  { word: "weary", emoji: "😴", hint: "Very tired out" },
  { word: "wince", emoji: "😬", hint: "To flinch when something hurts" },
  { word: "yield", emoji: "🌱", hint: "To give way — or how much a crop produces" },
  { word: "zesty", emoji: "🍋", hint: "Full of sharp, lively flavour" },
];

/* ---------- 👑 grown-up — 5 letters, real adult vocabulary ---------- */
const WG_GROWN = [
  { word: "adage", emoji: "📜", hint: "A short old saying that carries a truth" },
  { word: "aloof", emoji: "🧊", hint: "Distant and uninterested in joining in" },
  { word: "augur", emoji: "🔮", hint: "To foretell — or a sign of what is coming" },
  { word: "banal", emoji: "🥱", hint: "So ordinary it has become boring" },
  { word: "bland", emoji: "🍚", hint: "Dull, with no strong flavour or character" },
  { word: "bough", emoji: "🌳", hint: "A main branch of a tree" },
  { word: "brine", emoji: "🧂", hint: "Very salty water" },
  { word: "cache", emoji: "📦", hint: "A hidden store of supplies or data" },
  { word: "cadre", emoji: "👥", hint: "A small trained core group within an organisation" },
  { word: "decry", emoji: "📢", hint: "To condemn something publicly" },
  { word: "deign", emoji: "🙄", hint: "To lower yourself to do something" },
  { word: "demur", emoji: "🙅", hint: "To politely object or hesitate" },
  { word: "dirge", emoji: "🎻", hint: "A slow, mournful song for the dead" },
  { word: "dogma", emoji: "📖", hint: "Beliefs laid down as beyond question" },
  { word: "eclat", emoji: "✨", hint: "Brilliant, dazzling success" },
  { word: "edict", emoji: "⚖️", hint: "An official order from someone in power" },
  { word: "elegy", emoji: "🕯️", hint: "A poem of mourning" },
  { word: "epoch", emoji: "⏳", hint: "A long, distinct period of history" },
  { word: "ethos", emoji: "🧭", hint: "The guiding spirit or character of a group" },
  { word: "extol", emoji: "🎺", hint: "To praise something highly" },
  { word: "facet", emoji: "💎", hint: "One flat cut side — or one aspect of something" },
  { word: "feint", emoji: "🤺", hint: "A fake move made to fool an opponent" },
  { word: "flout", emoji: "🚫", hint: "To break a rule openly and without shame" },
  { word: "forte", emoji: "🎯", hint: "The thing you are strongest at" },
  { word: "genre", emoji: "🎬", hint: "A category of art, music or writing" },
  { word: "guile", emoji: "🦊", hint: "Sly cleverness used to trick people" },
  { word: "idyll", emoji: "🌾", hint: "A perfect, peaceful, picture-book scene" },
  { word: "imbue", emoji: "🎨", hint: "To fill something through and through with a quality" },
  { word: "inane", emoji: "🤪", hint: "Silly and completely without sense" },
  { word: "junta", emoji: "🎖️", hint: "A group of officers ruling after a takeover" },
  { word: "knell", emoji: "🔔", hint: "The slow tolling of a bell for a death" },
  { word: "lapse", emoji: "⌛", hint: "A slip — or a stretch of time slipping by" },
  { word: "lucid", emoji: "💡", hint: "Clear, sharp and easy to understand" },
  { word: "maxim", emoji: "🧾", hint: "A short rule to live by" },
  { word: "mores", emoji: "🏛️", hint: "The customs and manners a society lives by" },
  { word: "nadir", emoji: "📉", hint: "The very lowest point" },
  { word: "nexus", emoji: "🕸️", hint: "The central link where everything connects" },
  { word: "niche", emoji: "🕳️", hint: "A small perfect spot, or a narrow specialty" },
  { word: "parry", emoji: "🤺", hint: "To turn aside a blow — or an awkward question" },
  { word: "piety", emoji: "🙏", hint: "Deep religious devotion" },
  { word: "pique", emoji: "😤", hint: "A flash of irritation — or to stir up interest" },
  { word: "prose", emoji: "📝", hint: "Ordinary written language, as opposed to poetry" },
  { word: "purge", emoji: "🧹", hint: "To remove something completely and forcefully" },
  { word: "quash", emoji: "🔨", hint: "To put down or cancel entirely" },
  { word: "quell", emoji: "🌊", hint: "To calm or crush a disturbance" },
  { word: "rebut", emoji: "🗣️", hint: "To argue back against a claim with evidence" },
  { word: "regal", emoji: "👑", hint: "Splendid, in the manner of a monarch" },
  { word: "rogue", emoji: "🃏", hint: "A likeable rascal — or one that goes off alone" },
  { word: "sable", emoji: "⚫", hint: "Deep black — or a dark glossy fur" },
  { word: "salve", emoji: "🧴", hint: "A soothing ointment" },
  { word: "scion", emoji: "🌿", hint: "A descendant of a notable family" },
  { word: "sepia", emoji: "🟤", hint: "The warm brown of very old photographs" },
  { word: "skein", emoji: "🧶", hint: "A loose coil of yarn" },
  { word: "sloth", emoji: "🦥", hint: "Laziness — and the slow tree-dwelling animal" },
  { word: "snide", emoji: "😒", hint: "Mocking in a sneaky, indirect way" },
  { word: "spurn", emoji: "🚷", hint: "To reject something with scorn" },
  { word: "staid", emoji: "🎩", hint: "Settled, serious and unadventurous" },
  { word: "stoic", emoji: "🗿", hint: "Enduring hardship without complaint" },
  { word: "sully", emoji: "🩸", hint: "To stain or spoil a good name" },
  { word: "tacit", emoji: "🤐", hint: "Understood without ever being said aloud" },
  { word: "tenet", emoji: "📐", hint: "A core principle of a belief system" },
  { word: "terse", emoji: "✂️", hint: "Short and to the point, maybe rudely so" },
  { word: "tithe", emoji: "💰", hint: "A tenth part, given away" },
  { word: "trite", emoji: "🔁", hint: "Worn out from being said far too often" },
  { word: "tryst", emoji: "💌", hint: "A secret meeting between lovers" },
  { word: "unify", emoji: "🤝", hint: "To bring separate parts together into one" },
  { word: "usurp", emoji: "🪑", hint: "To seize a position that isn't yours" },
  { word: "vapid", emoji: "🫙", hint: "Empty, flat and lifeless" },
  { word: "verve", emoji: "⚡", hint: "Energy and enthusiasm in whatever you do" },
  { word: "wield", emoji: "⚔️", hint: "To hold and use power, or a weapon" },
  { word: "wrest", emoji: "🪢", hint: "To pull something away by force" },
];

/* ---------- extra words kids may TYPE (belt and braces on top of
     the big DICT4/DICT5 lists in dictionary.js) ---------- */
const WG_EXTRA5 = [
  "about", "above", "actor", "again", "alarm", "angel", "angry", "apron",
  "arrow", "baker", "bakes", "bears", "bench", "bingo", "black",
  "blame", "blank", "blast", "block", "bloom", "board", "boats",
  "bones", "books", "boots", "brain", "brave", "brush",
  "cabin", "cakes", "cards", "catch", "chalk",
  "charm", "chase", "cheek", "chess", "chest", "chief", "child",
  "chimp", "clean", "clear", "click", "color", "crane", "creek",
  "crisp", "crumb", "diary", "drink", "drums", "ducks",
  "elbow", "every", "fifty", "fight", "first",
  "flash", "float", "floor", "flour", "found", "fries", "front",
  "fruit", "funny", "games", "glass", "globe", "goats",
  "grass", "great", "hello", "hills", "igloo",
  "jolly", "jumbo", "knife", "lamps", "laugh", "learn", "lions",
  "lucky", "maple", "march", "marry", "metal", "mixer", "month",
  "mouth", "mummy", "noise", "north", "olive",
  "pedal", "phone", "pixel", "plums", "polar", "pouch", "power",
  "press", "price", "pride", "prize", "proud", "quick", "quilt",
  "radio", "rainy", "ranch", "reach", "ready", "roads", "rocks",
  "round", "royal", "sandy", "scout", "seeds", "shape",
  "share", "sheet", "shell", "shine", "shirt", "shore",
  "sight", "slide", "slime", "small", "snack",
  "sneak", "snowy", "socks", "solar", "space", "spark", "spend",
  "spice", "sport", "spray", "stamp", "stars", "start", "steam",
  "stick", "stork", "straw", "stump",
  "table", "teddy", "teeth", "thumb", "tiger", "today",
  "trees", "trick", "trunk", "twins", "uncle", "watch", "worms", "yummy",
];
const WG_EXTRA4 = [
  "bake", "blue", "book", "calm", "camp", "card", "city",
  "club", "cold", "cool", "cube", "dark", "desk",
  "dive", "doll", "down", "drop", "easy", "fast", "feet",
  "film", "fire", "foot", "game", "gate", "girl",
  "good", "grow", "hare", "hill", "home", "hope", "hour",
  "jump", "kind", "lake", "land", "left", "lime", "love",
  "mask", "mint", "mole", "nice", "note", "palm",
  "pink", "play", "plum", "pool", "road", "rock",
  "sand", "seed", "sing", "slow", "soft", "tail", "team",
  "town", "toys", "warm", "wind", "wing", "yard", "zoom",
];
